### ISSUE TITLE
Add option to process yearly data

### ISSUE THREAD

**Issue by perrette** [iiasa/rime#29]
First mentioned by @NiklasSchwind [here](https://github.com/iiasa/rime/issues/23#issue-2473505220). @NiklasSchwind sorry I don't remember what this refers to. Because we are dealing with daily right now? (I can't remember at the moment because I have been working with various versions ; possibly it will become clear when I look again into the code but don't hesitate to comment on this).

**Comment by NiklasSchwind** [comment]
Hey Mahé, with the current code, I could just preprocess indicators that can be aggregated to a monthly resolution and not annually defined indicators. So e.g. when I have simulations rx1day as an input, I would only have one value per grid point and year. This case can currently not be processed using the preprocessing code as it requires monthly data.

**Comment by perrette** [comment]
Ok. Perhaps we can work with a concrete case - like the rx1day indicator you mention, and I'll make sure it is handled appropriately.

**Comment by NiklasSchwind** [comment]
Yes! You could also use the already preprocessed Kotz et al. indicators in this directory: /mnt/PROVIDE/isimip/ISIMIP3b/SecondaryInputData/climate/atmosphere/bias-adjusted/global/yearly

**Comment by perrette** [comment]
See the new `indicator` group and `frequency` keywork in the config.toml file.

```toml
[indicator.rx5day]
frequency = "yearly"
historical = false
transform = "baseline_change_percent"
projection_baseline = [1995, 2014] # this also apply to ISIMIP2b
```
